# Generated by Django 2.2.6 on 2019-12-02 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20191201_1837'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='posterURL',
            field=models.CharField(default='https://m.media-amazon.com/images/M/MV5BNWM4M2QwOWUtNGMwMS00Nzg2LTg0YjktYTU4M2ZhYTMwYTU5XkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_UX182_CR0,0,182,268_AL_.jpg', max_length=250),
        ),
        migrations.AddField(
            model_name='movie',
            name='year',
            field=models.CharField(default='5555', max_length=6),
        ),
    ]
